packages:
  - .
  - submodule/markdown-wc/js
  - submodule/lix/packages/js-sdk
  - vendor/lix-legacy/packages/js-kysely
  - vendor/lix-legacy/packages/react-utils
  - '!submodule/lix/packages/**/dist'

onlyBuiltDependencies:
  - electron
